config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :restaurants do
  resources :reviews, only: [:new, :create]
end
root to: "restaurants#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(name: params[:restaurant][:name], address: params[:restaurant][:address], phone_number: params[:restaurant][:phone_nubmer], category: params[:restaurant][:category][0])
    @restaurant.save
    redirect_to root_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(name: params[:restaurant][:name], address: params[:restaurant][:address], phone_number: params[:restaurant][:phone_nubmer], category: params[:restaurant][:category][0])
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to root_path
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(content: params[:review][:content], rating: params[:review][:rating])
    @review.save
    redirect_to restaurant_path(@restaurant)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar-wagon">
      <!-- Logo -->
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo.png" %>
      <% end %>

      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">

        <!-- Links -->
        <%= link_to "Restaurants", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Add", new_restaurant_path, class: "navbar-wagon-item navbar-wagon-link" %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Restaurants", root_path %></li>
            <li><%= link_to "Add", new_restaurant_path %></li>
          </ul>
        </div>
      </div>
    </div>


    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="navigation">
  <%= link_to @restaurant.name, restaurant_path(@restaurant) %>
</div>

<div class="container">
  <%= simple_form_for (@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, :as => :check_boxes, :collection => [['Chinese', :chinese], ['Italian', :italian], ['Japanese', :japanese], ['French', :french], ['Belgian', :belgian]], :include_hidden => false %>
    <%= f.submit "Confirm", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
  <ul>
    <% @restaurants.each do |r| %>
    <div class="post-container">
      <div class="post-img">
        <p><%= image_tag "resto.jpg", id: "img-resto"  %></p>
      </div>

      <div class="post-content">
      <li>
        <strong class="post-title"><%= link_to r.name, restaurant_path(r) %></strong>
        <p><%= r.address %></p>
      </li>
      </div>
    </div>

    <% end %>
  </ul>

app/views/restaurants/new.html.erb
<div class="navigation">
  <%= link_to "Home", root_path %>
</div>

<div class="container">
  <%= simple_form_for (@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, :as => :check_boxes, :collection => [['Chinese', :chinese], ['Italian', :italian], ['Japanese', :japanese], ['French', :french], ['Belgian', :belgian]], :include_hidden => false %>
    <%= f.submit "Confirm", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="navigation">
  <%= link_to "Home", root_path %>
</div>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://cdn1.buuteeq.com/upload/18234/le-restaurant-3-1.jpg');">

  <div class="banner-content">
     <h1><%= @restaurant.name %></h1>
     <p><em><%= @restaurant.address %></em></p>
       <%= link_to "Edit", edit_restaurant_path, class: 'btn btn-success' %>
       <%= link_to "Add review", new_restaurant_review_path(@restaurant), class: "btn btn-danger" %>
  </div>
</div>



<div class="container">
  <div class="row comments">
    <div class="col-sm-offset-3 col-sm-6">
      <% @restaurant.reviews.each do |r| %>
        <p><strong>Commentaire #<%= r.id %></strong></p>
        <p><strong>Rating :</strong> <%= "*" * r.rating %></p>
        <p><%= r.content %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="navigation">
  <%= link_to @restaurant.name, root_path %>
</div>

<div class="container">
  <%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Validate", class: "btn btn-primary" %>
<% end %>
</div>